// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TzWatch.Http")>]
[<assembly: AssemblyProductAttribute("TzWatch")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-04-08T00:00:00.0000000+02:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","dced9cf1d38fe8ed034e3670504199f200fdf55d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TzWatch.Http"
    let [<Literal>] AssemblyProduct = "TzWatch"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-04-08T00:00:00.0000000+02:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "dced9cf1d38fe8ed034e3670504199f200fdf55d"
