// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TzWatch.Http")>]
[<assembly: AssemblyProductAttribute("TzWatch")>]
[<assembly: AssemblyVersionAttribute("0.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-10T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.5")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","589b265c815e346bcf3db0442c499032c1dfbdd3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TzWatch.Http"
    let [<Literal>] AssemblyProduct = "TzWatch"
    let [<Literal>] AssemblyVersion = "0.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-10T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.5"
    let [<Literal>] AssemblyInformationalVersion = "0.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "589b265c815e346bcf3db0442c499032c1dfbdd3"
