// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TzWatch.Lib")>]
[<assembly: AssemblyProductAttribute("TzWatch")>]
[<assembly: AssemblyVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-06-21T00:00:00.0000000+02:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","3b9f5c8920015a0fbcceff1a9ae31e5630b749cd")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TzWatch.Lib"
    let [<Literal>] AssemblyProduct = "TzWatch"
    let [<Literal>] AssemblyVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-06-21T00:00:00.0000000+02:00"
    let [<Literal>] AssemblyFileVersion = "0.2.2"
    let [<Literal>] AssemblyInformationalVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "3b9f5c8920015a0fbcceff1a9ae31e5630b749cd"
