// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TzWatch.Lib")>]
[<assembly: AssemblyProductAttribute("TzWatch")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-09T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","cc15b645f78033188ad66463deec982023f15d84")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TzWatch.Lib"
    let [<Literal>] AssemblyProduct = "TzWatch"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-09T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "cc15b645f78033188ad66463deec982023f15d84"
