name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0"
    - name: Restore tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --test-adapter-path:. --logger:junit
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        comment_title: Unit Test Statistics
        hide_comments: all but latest
        comment_on_pr: true
        files: ./TzWatch.Test/TestResults/**/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
