// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TzWatch.Test")>]
[<assembly: AssemblyProductAttribute("TzWatch")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-03-01T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8ee47e8d97d17afa6992b6debdf745bbe95f79a5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TzWatch.Test"
    let [<Literal>] AssemblyProduct = "TzWatch"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-03-01T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8ee47e8d97d17afa6992b6debdf745bbe95f79a5"
